### ISSUE TITLE
Cannot use the addon

### ISSUE THREAD

**Issue by savdev11** [ddev/ddev-varnish#19]
Hello, i'm trying to install and use varnish on a ddev drupal 10 multisite environment. I launched ddev get ddev/ddev-varnish and
ddev restart and this was the output: `yaml: line 3: did not find expected node content
Failed to restart project: ComposeCmd failed to run 'COMPOSE_PROJECT_NAME=ddev-project docker-compose -f /home/user1/projects/project/.ddev/.ddev-docker-compose-base.yaml -f /home/user1/projects/project/.ddev/docker-compose.varnish-extras.yaml -f /home/user1/projects/project/.ddev/docker-compose.varnish.yaml config', action='[config]', err='exit status 15', stdout='', stderr='yaml: line 3: did not find expected node content'`.

docker-compose.varnish-extras.yaml's content:

```
#ddev-generated
# This is the second half of the trick that puts varnish "in front of" the web
# container, just by switching the names.
{{  := "ddev.site" }}
{{ if .DdevGlobalConfig.project_tld }}{{  = .DdevGlobalConfig.project_tld }}{{ end }}
{{ if .DdevProjectConfig.project_tld }}{{  = .DdevProjectConfig.project_tld }} {{ end }}
{{  := print "novarnish." .DdevProjectConfig.name "."   }}
{{  := print "."  ",novarnish." }}
{{ if .DdevProjectConfig.additional_hostnames }}
{{  = print  "," "novarnish." (.DdevProjectConfig.additional_hostnames | join ) "."  }}
{{ end }}
{{ if .DdevProjectConfig.additional_fqdns }}
{{  = print  "," "novarnish." ( .DdevProjectConfig.additional_fqdns | join ",novarnish." )   }}
{{ end }}
services:
  web:
    environment:
    - VIRTUAL_HOST={{  }}
```

**Comment by jedubois** [comment]
@savdev11 , can you give us a bit more context on your configuration, e.g. what does your ddev config.yaml look like?

**Comment by savdev11** [comment]
> @savdev11 , can you give us a bit more context on your configuration, e.g. what does your ddev config.yaml look like?

Sure,
config.yaml:

```
name: project
type: drupal10
docroot: web
php_version: "8.1"
webserver_type: nginx-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
database:
  type: mariadb
  version: "10.3"
nfs_mount_enabled: false
mutagen_enabled: false
use_dns_when_possible: true
composer_version: "2"
disable_settings_management: true
web_environment: []
nodejs_version: "16"
```

config.multisite.yaml:
```
additional_hostnames:
  - roma
  - milano
hooks:
  post-start:
  - exec: mysql -uroot -proot -e "CREATE DATABASE IF NOT EXISTS roma; GRANT ALL ON roma.* to 'db'@'%';"
    service: db
  - exec: mysql -uroot -proot -e "CREATE DATABASE IF NOT EXISTS milano; GRANT ALL ON milano.* to 'db'@'%';"
    service: db
```
I installed a drupal 10 project and added this additional hostnames.
