### ISSUE TITLE
docker-compose.varnish-extras.yaml has a lot of extra new lines

### ISSUE THREAD

**Issue by mglaman** [ddev/ddev-varnish#24]
The generated `docker-compose.varnish-extras.yaml` has a lot of empty lines. It's not a huge problem, but it looks like all of the `{{ CONDITION }}` in the `install.yaml` turn into empty lines.

```
#ddev-generated
# This is the second half of the trick that puts varnish "in front of" the web
# container, just by switching the names.







services:
  web:
    environment:
    - VIRTUAL_HOST=novarnish.SITE_NAME.ddev.site
```
